### ISSUE TITLE
How do I build this mod

### ISSUE THREAD

**Issue by ghost** [Mechinsam/SpearThyself#3]
THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS. THIS IS A VIRUS.

**Comment by Mechinsam** [comment]
dotnet build -c Release
